---
title: "Targeted record swapping"
author: "Statistic Austria"
date: "27 8 2018"
output: beamer_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Implementation

+ On [https://github.com/sdcTools/recordSwapping](https://github.com/sdcTools/recordSwapping)
+ C++ contained inside dummy-R-Package (src/recordSwap/)
+ R-Code was just used for testing
+ C++ Code does not depend on R installment or any R-Functions
+ C++ Code uses only stl containers
    
    + no need (yet?) to use more specialized libraries


## Parameter

+ Rectangular Data Set
+ Variables which define *similar* households, like household size ect...

    + Used so that only *similar* households are swapped with each other
    
+ Risk-Variables to calculate Risk (now only 1/counts)
+ Households ID
+ Minimum number of counts for non-high risk households
+ Swaprate value between 0 and 1
+ Seed for random number generator


## Parameter

+ Describtion of C++ Code:

    1. Define risk for each household and over which geographic hierarchy the household needs to be swapped
    2. Start at highest hierarchy and swapp all households with high risk at the highest hierarchy
        
        + Randomly draw donor set of households which does not belong to the current geography
        
    3. At the lowest hierarchy level determine number of households which need to be swapped (according to swaprate)
    4. If already more households with high risk have been swapped here do not additionally swap mroe households
    5. Otherwise swap more households so that at least swaprate*Populationsize households have been swapped

## Differences to SAS Code

+ Functionality does differ from original SAS-Code

    + also because the implementation is more straightforward then 

+ Define Risk

    + SAS-Code: per risk variable and geographic variable
    + C++-Code: combination of all risk variables per geographic variable

## Differences to SAS Code (2)

+ Swap Records

    + SAS-Code: Swaps occur in every gegraphic hierarchy; swap and donor households are sampled in each hierarchy level
    + C++-Code: Swaps occur mainly in lowest hierachy; high risk households are always swapped; in lowest hierachy if any, the remaining number of households is swapped

+ Donor households

    + SAS-Code: Households with high risks are preferred in donor set
    + C++-Code: Households with low risks are preferred in donor set


## Differences to SAS Code (3)

+ Number of Swaps

    + SAS-Code: Number of swaps is distributed among lower level geo-hierarchies taking into account number of high risk households
    + C++-Code: Number of swaps proportional to population size according to swaprate

+ Probability

    + SAS-Code: determined using number of high risk households, sampling size and non imputed households
    + C++-Code: only inverse number of counts


