---
title: "Questions"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Questions on SAS-Code

+ Risk in SAS-Code is calculated for each hierarchy-level and **risk variable** seperately, correct?
    + What about combinations of risk variables?

+ Variable-specific risks are then averaged for each hierarchy and if this risk exceeds a specific (user defined?) threshold the household gets a flag for high risk and has to be swapped?
    + Is it considered over which hierarchy level a household needs to be swapped?
    + 

+ Swap-Rate is applied at highest level and distributed among lower levels taking into account the number of high risk households in each level?
    + Would it not suffice to distribute it proportional to population size?

+ Is the random swapping applied to all hierarchy levels or only the lowest one, meaning that at higher hierarchies only households which must be swapped are swapped, and at the lowest the remaining number of households are swapped according to the swap-ratio?

+ Are only households with the same household size swapped with each other, or can this vary?

+ Is there a formal documentation on how the probability vector for sampling is derived? Right now we are just using 1/counts.


