# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

recordSwap_cpp <- function(data, similar, hierarchy, risk, hid, th, swaprate, seed = 123456L) {
    .Call(`_recordSwapping_recordSwap_cpp`, data, similar, hierarchy, risk, hid, th, swaprate, seed)
}

setLevels_cpp <- function(data, hierarchy, risk, hid, th) {
    .Call(`_recordSwapping_setLevels_cpp`, data, hierarchy, risk, hid, th)
}

orderData_cpp <- function(data, orderIndex) {
    .Call(`_recordSwapping_orderData_cpp`, data, orderIndex)
}

test_randSample_cpp <- function(B, ID, N, prob, seed) {
    .Call(`_recordSwapping_test_randSample_cpp`, B, ID, N, prob, seed)
}

setRisk_cpp <- function(data, hierarchy, risk, hid) {
    .Call(`_recordSwapping_setRisk_cpp`, data, hierarchy, risk, hid)
}

